#function file
import turtle
bob=turtle.Turtle()

def polygon(sides,distance,color):
    bob.color(color)
    bob.begin_fill()
    angle=360/sides
    for times in range(sides):
        bob.forward(distance)
        bob.right(angle)
    bob.end_fill()

def polygon2(sides,distance,color):
    bob.color(color)
    angle=360/sides
    for times in range(sides):
        bob.forward(distance)
        bob.right(angle)

def jump(x,y):
    bob.penup()
    bob.goto(x,y)
    bob.pendown()

def star(distance,color):
    for times in range(5):
        bob.color(color)
        bob.forward(distance)
        bob.right(144)

def mstar(distance,color):
    bob.color(color)
    bob.begin_fill()
    for times in range(5):
        bob.forward(distance)
        bob.right(144)
    bob.end_fill()
    bob.forward(distance*.5)
    bob.right(90)
    bob.right(90)
    bob.color("black")
    bob.penup()
    bob.forward(distance*.1)
    bob.left(90)
    bob.forward(distance*.05)
    bob.pendown()
    bob.width(distance*.04)
    bob.forward(distance*.1)
    bob.right(180)
    bob.forward(distance*.1)
    bob.right(180)
    bob.color("white")
    bob.width(distance*.02)
    bob.penup()
    bob.forward(distance*.025)
    bob.pendown()
    bob.forward(distance*.05)
    bob.penup()
    bob.forward(distance*.025)
    bob.forward(distance*.1)
    bob.right(180)
    bob.forward(distance*.1)
    bob.right(90)
    bob.forward(distance*.2)
    bob.left(90)
    bob.forward(distance*.1)
    bob.right(180)
    bob.color("black")
    bob.pendown()
    bob.width(distance*.04)
    bob.forward(distance*.1)
    bob.right(180)
    bob.forward(distance*.1)
    bob.right(180)
    bob.color("white")
    bob.width(distance*.02)
    bob.penup()
    bob.forward(distance*.025)
    bob.pendown()
    bob.forward(distance*.05)
    bob.color("black")
    bob.penup()
    bob.forward(distance*.025)
    bob.right(90)
    bob.forward(distance*.5)
    bob.forward(distance*.1)
    bob.right(90)
    bob.forward(distance*.1)
    bob.forward(distance*.05)
    bob.right(90)
    bob.pendown()
    bob.speed(2)
    bob.width(1)

def mstaro(distance,width,color):
    bob.speed(0)
    bob.color("black")
    bob.width(width)
    for times in range(5):
        bob.forward(distance)
        bob.right(144)
    bob.color(color)
    bob.width(5)
    bob.begin_fill()
    for times in range(5):
        bob.forward(distance)
        bob.right(144)
    bob.end_fill()
    bob.forward(distance*.5)
    bob.right(90)
    bob.right(90)
    bob.color("black")
    bob.penup()
    bob.forward(distance*.1)
    bob.left(90)
    bob.forward(distance*.05)
    bob.pendown()
    bob.width(distance*.04)
    bob.forward(distance*.1)
    bob.right(180)
    bob.forward(distance*.1)
    bob.right(180)
    bob.color("white")
    bob.width(distance*.02)
    bob.penup()
    bob.forward(distance*.025)
    bob.pendown()
    bob.forward(distance*.05)
    bob.penup()
    bob.forward(distance*.025)
    bob.forward(distance*.1)
    bob.right(180)
    bob.forward(distance*.1)
    bob.right(90)
    bob.forward(distance*.2)
    bob.left(90)
    bob.forward(distance*.1)
    bob.right(180)
    bob.color("black")
    bob.pendown()
    bob.width(distance*.04)
    bob.forward(distance*.1)
    bob.right(180)
    bob.forward(distance*.1)
    bob.right(180)
    bob.color("white")
    bob.width(distance*.02)
    bob.penup()
    bob.forward(distance*.025)
    bob.pendown()
    bob.forward(distance*.05)
    bob.color("black")
    bob.penup()
    bob.forward(distance*.025)
    bob.right(90)
    bob.forward(distance*.5)
    bob.forward(distance*.1)
    bob.right(90)
    bob.forward(distance*.1)
    bob.forward(distance*.05)
    bob.right(90)
    bob.pendown()
    bob.speed(2)
    bob.width(1)

def explosion(distance,color):
    bob.color(color)
    bob.begin_fill()
    for times in range(8):
        bob.forward(distance)
        bob.right(135)
    bob.end_fill()
